version: '3.8'

services:
  llm-usage-monitoring:
    build: .
    container_name: llm-usage-monitoring
    ports:
      - "8080:80"
    environment:
      - OPENAI_API_KEY=your_openai_api_key
      - MQTT_BROKER=192.168.1.100  # Replace with your broker's IP or hostname
      - MQTT_PORT=1883
      - MQTT_TOPIC=homeassistant/sensor/openai_cost
      - MQTT_USERNAME=your_mqtt_username
      - MQTT_PASSWORD=your_mqtt_password